"""add timeline events table

Revision ID: 6a7f6411a3e7
Revises: 5d4eb983a620
Create Date: 2026-03-28 03:43:57.600549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a7f6411a3e7'
down_revision: Union[str, Sequence[str], None] = '5d4eb983a620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'STATUS_CHANGED', 'SEVERITY_CHANGED', 'ASSIGNED', 'UNASSIGNED', 'PROCESSING_STARTED', 'PROCESSING_COMPLETED', 'PROCESSING_FAILED', 'DUPLICATE_DETECTED', 'CLUSTER_JOINED', 'CLUSTER_CREATED', 'AI_ANALYSIS_COMPLETED', 'AI_REVIEW_SUBMITTED', 'SEVERITY_SCORED', 'SEVERITY_OVERRIDDEN', 'NOTE_ADDED', 'ESCALATED', 'ACKNOWLEDGED', 'RESOLVED', 'REOPENED', name='event_type'), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=200), nullable=True),
    sa.Column('event_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_event_type'), 'timeline_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_timeline_events_incident_id'), 'timeline_events', ['incident_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_occurred_at'), 'timeline_events', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_events_occurred_at'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_incident_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_event_type'), table_name='timeline_events')
    op.drop_table('timeline_events')
    # ### end Alembic commands ###
