"""create incidents table

Revision ID: 79d898738194
Revises: 
Create Date: 2026-03-28 01:59:05.035405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d898738194'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'INVESTIGATING', 'RESOLVED', 'CLOSED', name='incident_status'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='incident_severity'), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=True),
    sa.Column('service', sa.String(length=200), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('cluster_id', sa.String(length=64), nullable=True),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_root_cause', sa.Text(), nullable=True),
    sa.Column('ai_suggested_actions', sa.Text(), nullable=True),
    sa.Column('ai_reviewed', sa.Boolean(), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_cluster_id'), 'incidents', ['cluster_id'], unique=False)
    op.create_index('ix_incidents_detected_at', 'incidents', ['detected_at'], unique=False)
    op.create_index(op.f('ix_incidents_fingerprint'), 'incidents', ['fingerprint'], unique=False)
    op.create_index('ix_incidents_source', 'incidents', ['source'], unique=False)
    op.create_index('ix_incidents_status_severity', 'incidents', ['status', 'severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incidents_status_severity', table_name='incidents')
    op.drop_index('ix_incidents_source', table_name='incidents')
    op.drop_index(op.f('ix_incidents_fingerprint'), table_name='incidents')
    op.drop_index('ix_incidents_detected_at', table_name='incidents')
    op.drop_index(op.f('ix_incidents_cluster_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
