"""add score history table

Revision ID: 9b47c4270bfb
Revises: 679ffdc4fe0f
Create Date: 2026-03-28 03:06:40.980989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b47c4270bfb'
down_revision: Union[str, Sequence[str], None] = '679ffdc4fe0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('previous_score', sa.Float(), nullable=True),
    sa.Column('severity_label', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('scored_by', sa.String(length=200), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('rule_details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_history_incident_id'), 'score_history', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_history_incident_id'), table_name='score_history')
    op.drop_table('score_history')
    # ### end Alembic commands ###
